version: 0.2

phases:
  pre_build:
    commands:
      - echo ========== RailsMigration ==========
      - aws ecs run-task --cluster arn:aws:ecs:$AWS_DEFAULT_REGION:$AWS_ACCOUNT_ID:cluster/maxi_app_cluster --task-definition maxi_app_task --launch-type FARGATE --overrides '{"containerOverrides":[{"name":"maxi_app_api","command":["rails","db:migrate"]}]}' --network-configuration "awsvpcConfiguration={subnets=[subnet-03aeda935a3b13b98,subnet-04a05f208a7e010b5],securityGroups=[sg-0c3815cfecde264e3],assignPublicIp=DISABLED}"
