version: 0.2

phases:
  install:
    commands:
      # # session-manager-pluginをインストール
      # - sudo yum install -y https://s3.amazonaws.com/session-manager-downloads/plugin/latest/linux_64bit/session-manager-plugin.rpm
      # - session-manager-plugin
  build:
    commands:
      - docker-compose -f docker-compose.yml run --rm api bundle exec rails db:migrate
  # post_build:
  #   commands:
  #     - echo ========== RailsMigration ==========
  #     - aws ecs run-task --cluster arn:aws:ecs:$AWS_DEFAULT_REGION:$AWS_ACCOUNT_ID:cluster/$CLUSTER_NAME --task-definition $TASK_NAME --launch-type FARGATE --overrides '{"containerOverrides":[{"name":"maxi_app_api","command":["rails","db:migrate"]}]}' --network-configuration "awsvpcConfiguration={subnets=[$SUBNET_ID_01,$SUBNET_ID_02],securityGroups=[$SECURITY_GROUP_ID],assignPublicIp=DISABLED}"
