version: '3'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_ROOT_HOST: '%'
    ports:
      - '3306:3306'
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql-data:/var/lib/mysql
  api:
    build: .
    volumes:
      - .:/maxi_app
      - public:/maxi_app/public
      - tmp:/maxi_app/tmp
    depends_on:
      - db
    stdin_open: true
    tty: true
  nginx:
    build:
      args:
        - ENVIRONMENT=local
      context: .
      dockerfile: ./nginx/Dockerfile
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - public:/maxi_app/public
      - tmp:/maxi_app/tmp
    ports:
      - "80:80"
    depends_on:
      - api
volumes:
  mysql-data:
    driver: local
  tmp:
  public:
