name: Ruby

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    # Docker起動
    - name: Build and up docker
      run: |
        docker-compose down
        docker-compose build
        docker-compose up -d

    # rubocop実行
    - name: Run rubocop
      run: docker-compose run --rm api bundle exec rubocop

    # Rspec実行
    - name: Run rspec
      run: |
        docker-compose run --rm api bundle exec rails db:create
        docker-compose run --rm api bundle exec rails db:migrate:reset
        docker-compose run --rm api bundle exec rspec
      env:
        MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
        MYSQL_USERNAME: ${{ secrets.MYSQL_USERNAME }}
        MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
        MYSQL_HOST: ${{ secrets.MYSQL_HOST }}
